### PR TITLE
Support upload to zenodo

### LINKED ISSUE #108: Add "Download all" link to the zenodo description page
Since zenodo itself doesn't provide a button for downloading all the files, it would be nice if we can auto generate a download all link to the description page.

### LINKED ISSUE #111: Are models downloadable as zip archives from zenodo?
Hello @oeway,

quick question: I wanted to try one of the modelzoo compliant networks @constantinpape has trained, brought up to spec and uploaded it (via the bioimageio uploader as it says on zenodo): [model](https://sandbox.zenodo.org/record/865618#.YMnEoCWxVpQ).

I'm not sure I've overlooked it, but it seems that all files have to be downloaded separately? Or is the a secret download all button somewhere?

Cheers

### PR DESCRIPTION
**Pull request by oeway**
This PR aims to ease the uploading process for users, essentially eliminate the hassle of uploading weights to zenodo, upload yaml to github and make PR. Here we use as our storage backend and upload the files directly with a custom UI.

closes https://github.com/bioimage-io/bioimage.io/issues/111
closes https://github.com/bioimage-io/bioimage.io/issues/108

### CODE REVIEW

**Comment by oeway** [comment]
@constantinpape Now the upload feature is more complete, could you please try it out  with the preview link generated above?

Right now, items will be uploaded to sandbox version of zenodo, so don't hesitate to upload test packages.

After uploading, an email will send to me and I can approve or reject whether the item should be listed in the bioimage-io community: https://sandbox.zenodo.org/communities/bioimage-io

**Comment by constantinpape** [comment]
> @constantinpape Now the upload feature is more complete, could you please try it out with the preview link generated above?
> 
> Right now, items will be uploaded to sandbox version of zenodo, so don't hesitate to upload test packages.

Awesome! I will give it a try later today.

**Comment by constantinpape** [comment]
@oeway I tried to upload with the following zip: https://oc.embl.de/index.php/s/zghIW2vqLKNCFcd
But when pressing "Ok" after importing the zip the menu does not continue and some errors are thrown in the console:
Screenshot from 2021-05-31 11-43-36

There were also some other minor issues I noticed:
- The model file inside of the zip had to be called `model.yaml`, but afaik we allow it to be called `<SOME_NAME>.model.yaml`.
- The format version is not copied from the yaml: it showed `0.1.0`, but the value in the yaml is `0.3.1`.
- The source field was empty, although the zip contains a (local) source file that is also listed in the yaml.

**Comment by oeway** [comment]
> @oeway I tried to upload with the following zip: https://oc.embl.de/index.php/s/zghIW2vqLKNCFcd
> But when pressing "Ok" after importing the zip the menu does not continue and some errors are thrown in the console:

@constantinpape 
Thanks! Somehow I cannot reproduce the issue with your file. Possibly because I made changes in the meantime. I am now able to proceed to the uploading step. Could you please try it again?
 
> There were also some other minor issues I noticed:
> 
> * The model file inside of the zip had to be called `model.yaml`, but afaik we allow it to be called `<SOME_NAME>.model.yaml`.

Yes, we had some discussion a while about when we place the model yaml inside a package, we should rename it to `model.yaml`. The thing is we will need some kind of fixed entrypoint (a bit like the `setup.py` file of a python package and  `index.html` page of a website), otherwise we will need to search within the package which is not always possible (e.g. on zenodo it will generate more requests). Plus, we don't want really multiple yaml in one package. 

And now while working on other RDF file, I am even thinking we should perhaps rename `model.yaml` to something more generic, so we can also pacakge datasets, notebooks, applications, and share the same entry point yaml file name. I thought about `config.yaml` but then noticed it might be confusing since we have `config` key in the `model.yaml`. I would propose something like `rdf.yaml`, `rdf.bioimage.io.yaml`, or `bioimage.io.yaml`.

> * The format version is not copied from the yaml: it showed `0.1.0`, but the value in the yaml is `0.3.1`.
We need to distinguish `version` and `format_version` here, in one of the onging PR, I propose that we add a `version` key to label the model itself. Imagine the model with the same name can also evolve, e.g. trained with more data, since the purpose is the same, one might want to use the exact same name, and we might not want to have distinct entries in bioimage.io. We simply want new users to use the new version of the model. In this case a `version` key would help. (Let's discuss more on the weekly meeting.)

> * The source field was empty, although the zip contains a (local) source file that is also listed in the yaml.

There is a collision in the definition of `source` key: https://github.com/bioimage-io/spec-bioimage-io/issues/85
I will remove it from the form now.

**Comment by constantinpape** [comment]
This seems to be a firefox issue. I still get the following issue there:
Screenshot from 2021-05-31 12-53-29

I tried with chromium and there it works. (I didn't proceed with the upload further, because I couldn't log into zenodo there, but I think that's an unrelated issue).
I have the following versions:
```
pape@mokshi:~$ firefox --version
Mozilla Firefox 88.0.1
pape@mokshi:~$ chromium --version
Chromium 91.0.4472.77 snap
```

**Comment by oeway** [comment]
> I tried with chromium and there it works. (I didn't proceed with the upload further, because I couldn't log into zenodo there, but I think that's an unrelated issue).
> I have the following versions:
> 
> ```
> pape@mokshi:~$ firefox --version
> Mozilla Firefox 88.0.1
> pape@mokshi:~$ chromium --version
> Chromium 91.0.4472.77 snap
> ```

Ok, but I just tried `Firefox 88.0.1 (64-bit)` on macOS and it worked. I had to allow popup window in the addrress bar to get the zenodo login window, maybe that's the problem for you? Maybe you blocked the popup window in Chrome too?

**Comment by constantinpape** [comment]
> Ok, but I just tried `Firefox 88.0.1 (64-bit)` on macOS and it worked. I had to allow popup window in the addrress bar to get the zenodo login window, maybe that's the problem for you? Maybe you blocked the popup window in Chrome too?

Still doesn't work for me. I disabled pop-up blockers and the errors in the console look like something else to me:
```
Uncaught TypeError: n is null
    a app.8d45b794.js:1
app.8d45b794.js:1
Invalid file type 
Object { name: Getter & Setter, dir: Getter & Setter, date: Getter & Setter, comment: Getter & Setter, unixPermissions: Getter & Setter, dosPermissions: Getter & Setter, _data: Getter & Setter, _dataBinary: Getter & Setter, options: Getter & Setter, … }
app.8d45b794.js:1
Error: Invalid deposit (841584), rdf.yaml or model.yaml is not defined in the metadata (as part of the "related_identifiers")
    b app.8d45b794.js:1
    f app.8d45b794.js:1
    e app.8d45b794.js:1
    l chunk-vendors.2a817465.js:95897
    I chunk-vendors.2a817465.js:95897
    t chunk-vendors.2a817465.js:95897
    n chunk-vendors.2a817465.js:1
    s chunk-vendors.2a817465.js:1
    promise callback*n chunk-vendors.2a817465.js:1
    s chunk-vendors.2a817465.js:1
    promise callback*n chunk-vendors.2a817465.js:1
    s chunk-vendors.2a817465.js:1
    o chunk-vendors.2a817465.js:1
    o chunk-vendors.2a817465.js:1
    t app.8d45b794.js:1
    r app.8d45b794.js:1
    l chunk-vendors.2a817465.js:95897
    I chunk-vendors.2a817465.js:95897
    t chunk-vendors.2a817465.js:95897
    n chunk-vendors.2a817465.js:1
    s chunk-vendors.2a817465.js:1
    o chunk-vendors.2a817465.js:1
    o chunk-vendors.2a817465.js:1
    formSubmitted app.8d45b794.js:1
    it chunk-vendors.2a817465.js:27078
    $emit chunk-vendors.2a817465.js:27078
    emitValues chunk-vendors.2a817465.js:1
    onSubmit chunk-vendors.2a817465.js:1
    handleSubmit chunk-vendors.2a817465.js:1
    s chunk-vendors.2a817465.js:1
    s chunk-vendors.2a817465.js:1
    a chunk-vendors.2a817465.js:1
    promise callback*c chunk-vendors.2a817465.js:1
    r chunk-vendors.2a817465.js:1
    r chunk-vendors.2a817465.js:1
    handleSubmit chunk-vendors.2a817465.js:1
    submit chunk-vendors.2a817465.js:1
    it chunk-vendors.2a817465.js:27078
    i chunk-vendors.2a817465.js:27078
    _wrapper chunk-vendors.2a817465.js:27078
```

Note that I am on Ubuntu 20.04. (And I think it works on chromium, I just don't have a PW manager there, so I can't so easily log into git / zenodo.)

**Comment by constantinpape** [comment]
> And now while working on other RDF file, I am even thinking we should perhaps rename `model.yaml` to something more generic, so we can also pacakge datasets, notebooks, applications, and share the same entry point yaml file name. I thought about `config.yaml` but then noticed it might be confusing since we have `config` key in the `model.yaml`. I would propose something like `rdf.yaml`, `rdf.bioimage.io.yaml`, or `bioimage.io.yaml`.

I agree, we should update this so we have a unified entry point.
I suggest we discuss this in a separate issue in the spec repo.

**Comment by oeway** [comment]
> Note that I am on Ubuntu 20.04. (And I think it works on chromium, I just don't have a PW manager there, so I can't so easily log into git / zenodo.)

Hmm,  I know the error, but don't know why it happens. I will investigate into that later. 

Maybe someone else can also try it. @FynnBe @esgomezm Could you test the upload feature when you have sometime?

**Comment by esgomezm** [comment]
Which browser or OS do you want to check?

**Comment by constantinpape** [comment]
> Which browser or OS do you want to check?

I think Linux + Firefox would be good if you have it available.

**Comment by esgomezm** [comment]
Hi! I played a bit with Linux + Fireforx and when uploading the zip file, it worked correctly. I got to the point in the image but without publishing the model. In Zenodo all the files were OK so I guess that this part will work also. 

What was a bit confusing is that the feature creates a new user with the github credentials which is different from the one I already had with the same github account. So now I have two zenodo accounts with the same name and different content? how can access one or the other one?

The interface says: "New changes will be added as a new version". This was kind of confusing. Does the upload feature allow updating a published version? Or do you mean that you need to make a new submission?
Screenshot from 2021-06-03 23-16-05



Then, I tried to upload the model but using the RDFX. When doing so, do we also need to upload the model.yaml? 
In any case, I tried it in both ways: uploading the zip file as before, and uploading the files in the zip, without being compressed. 
It outputs the following message:
Screenshot from 2021-06-03 23-13-55

Regarding GitHub - Zenodo permissions, when you give them for the first time, two contradictory messages appear (see the image). Do you think it could be possible to remove the second one saying invalid authorization request? 
Screenshot from 2021-06-03 23-12-28

**Comment by oeway** [comment]
@esgomezm Thanks for testing!

> Hi! I played a bit with Linux + Fireforx and when uploading the zip file, it worked correctly. I got to the point in the image but without publishing the model. In Zenodo all the files were OK so I guess that this part will work also.

Good!

> What was a bit confusing is that the feature creates a new user with the github credentials which is different from the one I already had with the same github account. So now I have two zenodo accounts with the same name and different content? how can access one or the other one?

Aha, this is because we are using the sandbox version of zenodo (https://sandbox.zenodo.org) for testing, so that requires a different account.

> The interface says: "New changes will be added as a new version". This was kind of confusing. Does the upload feature allow updating a published version? Or do you mean that you need to make a new submission?

I updated the text on the interface now. This basically means if you publish you can not remove it but you can change it by adding new versions. You can also test this feature, on the first screen if you specify an existing doi using option 3, then you should get a update existing deposit option.

> Then, I tried to upload the model but using the RDFX. When doing so, do we also need to upload the model.yaml?
In any case, I tried it in both ways: uploading the zip file as before, and uploading the files in the zip, without being compressed.
It outputs the following message:

I guess what happens is that you don't have `covers` specified in your RDF, can you confirm that? I have fixed the issue though by make it empty by default. 

In general, for issues like this it would also help if you can open the browser development tool and copy the error in the browser console.

> Regarding GitHub - Zenodo permissions, when you give them for the first time, two contradictory messages appear (see the image). Do you think it could be possible to remove the second one saying invalid authorization request?

Unfortunately not, this is the part implemented by Zenodo, we can however submit a github issue to them.

Anyway, please try the latest version (e.g refresh the page twice) and see if the issues still exists.

**Comment by esgomezm** [comment]
Hi @oeway! 

I'm trying to upload a model but now it doesn't work when uploading the files to zenodo:
image

**Comment by oeway** [comment]
@esgomezm Thank you for the report with console error. I just fixed it now.
Does this mean your RDF does not have a author field?

**Comment by esgomezm** [comment]
It has, but in which format? the list or the composite dict? :)

**Comment by oeway** [comment]
> It has, but in which format? the list or the composite dict? :)

We are still in 0.3.1 format right now, so it should be a list of strings.

**Comment by esgomezm** [comment]
Done!
The only thing is that with the size of the window I couldn't see the rolling circle so I click on upload a couple of times and the app created as many zenodo drafts as clicks

image

**Comment by esgomezm** [comment]
We opened pandora's box: 

I clicked on "list the model in the bioimage model zoo", but where can I find it? 
Should I upload this model.yaml to my github repo but I changing all the paths to weights so they point to the ones in zenodo? Otherwise, how is the model packager used?

**Comment by oeway** [comment]
> We opened pandora's box:
> 
> Now I should upload this model.yaml to my github repo but I should change all the paths to weights so they point to the ones in zenodo. Otherwise, I cannot use the packager, am I right?

I got an email about your model ;) see below:
Screenshot 2021-06-04 at 17 36 03

And I just approved the request, so you should see the new item in the model zoo now.

One idea is that you don't store models in the github repo at all, all models can be pulled from zenodo, and each partner can filter out the list with tags. 

We can still use the community partner github repo for validating, and testing the models with CIs, it will generate a json file with the testing reports for each model, with the possibility to black list some models from showing on the website.


Let me know what you think.

**Comment by esgomezm** [comment]
Ok, it sounds good.
I don't see it in the main bioimage.io webpage but in the preview.
I think it's a pity if these models wouldn't be linked to the model packager as they indeed ready for that. Otherwise, we need to go to Zenodo and download each file one by one.

@constantinpape you have the model available for testing :)  https://deploy-preview-104--bioimage.netlify.app/#/?id=10.5072%2Fzenodo.849111

**Comment by constantinpape** [comment]
> @constantinpape you have the model available for testing :) https://deploy-preview-104--bioimage.netlify.app/#/?id=10.5072%2Fzenodo.849111

Awesome! I will check it out later.

**Comment by oeway** [comment]
> I don't see it in the main bioimage.io webpage but in the preview.

That's because we are testing with sandbox zenodo


> I think it's a pity if these models wouldn't be linked to the model packager as they indeed ready for that. Otherwise, we need to go to Zenodo and download each file one by one.

@esgomezm There was an issue about the display of linked items, now it has been fixed, so you should got the packager by default. Unless you removed it from links when you upload it. 

Edit: however, the packager icon is shown but it won't work for now because I need to fix the link to the YAML file.

**Comment by tomburke-rse** [comment]
Just tried the Upload-feature: Works fine! :) Really nice. Only thing I'd change is the second step, which Esti mentioned before I think. I tried the N2V Model bundle, I only had to change the MDF name.
When clicking on "OK" you just get redirected wordlessly to Zenodo and I think I had to click "OK" 4 times (First time Zenodo Login, Log into Zenodo from Github, allow 3rd party tool and so on) until I could proceed.

And I'm really missing a "Download all" button on Zenodo, but that's another topic.

**Comment by oeway** [comment]
@tomburke-rse Thanks for testing it. 
> Only thing I'd change is the second step, which Esti mentioned before I think. I tried the N2V Model bundle, I only had to change the MDF name.

Let's discuss in today's meeting about the naming of the manifest file.

> When clicking on "OK" you just get redirected wordlessly to Zenodo and I think I had to click "OK" 4 times (First time Zenodo Login, Log into Zenodo from Github, allow 3rd party tool and so on) until I could proceed.

Right, there is easy way around it, I hope it won't cause too much confusion for the users. 

> And I'm really missing a "Download all" button on Zenodo, but that's another topic.

We will add a download all button to the zenodo description test then.

**Comment by constantinpape** [comment]
I tried this with 2 other setups, but ran into the following issues:

## Setup 1
OS: CentOS 8 (This is a VM @ EMBL)
Firefox: 78.11

I can go through the whole procedure and click "Upload as new Deposit".
However this fails with 
```
Failed to upload file: Error: Failed to update metadata, error: [{"field":"metadata.creators.0.name","message":"Not a valid string. Name is required."}]
```
I am trying to upload [this model](https://oc.embl.de/index.php/s/TYIybAuiJpSAvVJ), which should be 0.3.2 compliant.

## Setup 2
OS: Same
Chromium: 85.0

I come up to the zenodo login with github credentials but then it just resets to the Bioimage.Io site after a few seconds (not enough to enter credentials, esp. not with 2FA).

**Comment by oeway** [comment]
@constantinpape Thanks for the report and providing the test package. I debugged it and found out that I didn't implement the new `authors` format. I have now fixed it, please give the new version a try (you may need to reload twice).

No idea about the login issue, is there a chance to get a screen recording?

**Comment by constantinpape** [comment]
> please give the new version a try (you may need to reload twice).

Yes, it works now, Here's the uploaded model: https://sandbox.zenodo.org/record/865308#.YMkExSWxVpQ.

> No idea about the login issue, is there a chance to get a screen recording?

Sure. I also checked this locally now and the same issue occurs with chromium 91.0 (on Ubuntu 20.04). See screenrecording below; after a couple of seconds the zenodo github login tab just closes.

zenodo-2021-06-15_22 19 22

**Comment by oeway** [comment]
@constantinpape I just fixed the packager, and there are also some adjustment to fit the changes we have for `config`. Could you give it another try before we merge?

**Comment by oeway** [comment]
@constantinpape i saw your new upload: https://sandbox.zenodo.org/record/865994 please note that your docs file has unusual indentation which make the entire docs rendered as a code block. Removing the indentation should fix the issue.

**Comment by constantinpape** [comment]
@oeway I checked the uploader again (as you have already seen) and it works. The model packager also works,  but it does not include all files that need to be packaged: `documentation.md` and `environment.yaml` are missing:
Screenshot from 2021-06-16 23-01-22

Note that I did not list these in `attachments`, because I thought that the doc and dependency file should always be packaged. But if you think that this is rather an issue of the model and they should be added to attachments I can also fix this on the model side.

> @constantinpape i saw your new upload: https://sandbox.zenodo.org/record/865994 please note that your docs file has unusual indentation which make the entire docs rendered as a code block. Removing the indentation should fix the issue.

Thanks for checking. I will fix it in the code that generates this.

**Comment by constantinpape** [comment]
I found another issue: The `Download RDF` button on zenodo does not work for [this model](https://sandbox.zenodo.org/record/865994):
When I go to https://bioimage.io/#/p/zenodo:865994 I just see a white page.

**Comment by oeway** [comment]
> I found another issue: The `Download RDF` button on zenodo does not work for [this model](https://sandbox.zenodo.org/record/865994):
> 
> When I go to https://bioimage.io/#/p/zenodo:865994 I just see a white page.

Thanks for testing it again!
That's expected. As I mentioned earlier, I haven't implemented the download link yet, that's a preserved link. After merging it will show a popup message saying not implemented instead of a blank page.

I will delay the implementation of downloading from zenodo, since the recommended way is to download with the packager on bioimage.io.

Regarding the docs and dependency in the packager, i will fix that in the packager app. Also note that, we agreed that we will move source and dependencies to the weight format in 0.4.0.

**Comment by constantinpape** [comment]
> Thanks for testing it again!
> That's expected. As I mentioned earlier, I haven't implemented the download link yet, that's a preserved link. After merging it will show a popup message saying not implemented instead of a blank page.
> 
> I will delay the implementation of downloading from zenodo, since the recommended way is to download with the packager on bioimage.io.

OK, that sounds good.

> Regarding the docs and dependency in the packager, i will fix that in the packager app.

Awesome!

**Comment by esgomezm** [comment]
@oeway I’m checking the models from the uploader and the `source` button (<>) works differently. Instead of showing the model yaml it redirects you to zenodo. Do you think it would be possible to show the specs?

**Comment by oeway** [comment]
> @oeway I’m checking the models from the uploader and the `source` button (<>) works differently. Instead of showing the model yaml it redirects you to zenodo. Do you think it would be possible to show the specs?

Hi, sorry I forgot to change that, now fixed. 
~~Note that it will only work for newly uploaded models. Please upload a new model and see if it works.~~

**Comment by oeway** [comment]
All fixed now, except the login issue mentioned by @constantinpape 
Now merge.

**Comment by constantinpape** [comment]
> All fixed now, except the login issue mentioned by @constantinpape

I made #113 to keep track of these issues.

> Now merge.

Awesome. Thanks Wei!

**Pull request merged**
