### PR TITLE
Fix edit button

### PR DESCRIPTION
**Pull request by oeway**

### CODE REVIEW

**Comment by oeway** [comment]
@constantinpape could you try the preview and see if you can see the edit button and use it for updating items?

**Comment by constantinpape** [comment]
image

@oeway the preview doesn't work

**Comment by constantinpape** [comment]
Actually also happens on the main site now too:

image

**Comment by oeway** [comment]
Oops, sorry, it was from an update in the collection repo, fixed now: https://github.com/bioimage-io/collection-bioimage-io/pull/246

**Pull request merged**
