### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by FynnBe**
manifest -> collection RDF

### CODE REVIEW

**Comment by FynnBe** [comment]
@oeway is there a .svg of https://github.com/bioimage-io/bioimage.io/blob/FynnBe-patch-1/docs/community_partners/bioimage-io-community-partners.png? It would need an update as well...

**Comment by oeway** [comment]
> @oeway is there a .svg of https://github.com/bioimage-io/bioimage.io/blob/FynnBe-patch-1/docs/community_partners/bioimage-io-community-partners.png? It would need an update as well...

Hey, thanks for the PR, yes, I just shared the google docs with your embl email.

**Comment by FynnBe** [comment]
> Hey, thanks for the PR, yes, I just shared the google docs with your embl email.

Thanks! Do you mind if we add the exported .svg from that google sheet here?

**Comment by FynnBe** [comment]
the partner ci section still needs to be updated...

**Comment by oeway** [comment]
> > Hey, thanks for the PR, yes, I just shared the google docs with your embl email.
> 
> Thanks! Do you mind if we add the exported .svg from that google sheet here?

No, go ahead and do whatever you like!

**Comment by FynnBe** [comment]
this .svg can even be rendered in markdown directly...

**Comment by oeway** [comment]
> this .svg can even be rendered in markdown directly...

However, it seems my browser (Chrome) blocks it when you load it independently: https://raw.githubusercontent.com/bioimage-io/bioimage.io/eda0a990e56e463be955dfe854d562478dee6b9d/docs/community_partners/bioimage-io-community-partners.svg

I guess it's because the icons are not embedded. The browser console said: `Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.`.

Could you make sure it will render correctly? Otherwise I would go for png for consistency.

**Comment by FynnBe** [comment]
> Could you make sure it will render correctly? Otherwise I would go for png for consistency.

uhh, I see.. back to png is the simplest...

**Pull request merged**
