### PR TITLE
Fix deposit update

### LINKED ISSUE #118: How to update a model via upload button?
I am trying to update a model via the update button, however I am only shown that a nameclash exist, but not able to go forward to update the model with that name:

Screenshot from 2021-06-20 19-59-59

### PR DESCRIPTION
**Pull request by oeway**
This PR allows adding new versions to existing deposit, either via a DOI/DEPOSIT URL via option 3, or updated via the detected similar deposit item list.

Fixes https://github.com/bioimage-io/bioimage.io/issues/118

Thanks to @constantinpape reporting the issue.

### CODE REVIEW

**Comment by constantinpape** [comment]
While the update functionality seems to be working as expected, this PR introduces some other issue which prevents me from uploading any models; I see the following error message for any model I tried:
Screenshot from 2021-06-21 14-22-26
Note that uploading the model worked fine on the normal bioimage.io: https://sandbox.zenodo.org/record/869189#.YNCFjzqxUUE.

**Comment by oeway** [comment]
@constantinpape I cannot reproduce the issue, I downloaded the package with the packager: https://bioimage.io/#/p/zenodo:869189
Then use the zip package to test and it worked for me. Try the exported package? Or perhaps provide your current one if that is the issue.

**Comment by constantinpape** [comment]
Yes, it works now. Thanks!

**Comment by oeway** [comment]
OK, thanks, let's merge then!

**Pull request merged**
