### PR TITLE
Show test run in the model info page

### PR DESCRIPTION
**Pull request by Nanguage**
Preview:

model-interface-page-s

Current issues: 1. Slow loading speed of model interface plugin 2. Window size (mainly height) is not suitable 3. Long waiting time for model operation 4. User needs to manually input axes name

### CODE REVIEW

**Comment by cfusterbarcelo** [comment]
# Meeting Updates (11/09/2023)

## Notes
- Currently, running a model on a 3D image takes 2 to 3 minutes, which is longer than desired. We need to explore ways to reduce this time in the future.
- Display expected dimensions for input images to improve user understanding.
- Create a list of possible user errors, such as incorrect image dimensions, and generate user-friendly error messages.

## Action Items
- [ ] Add a download button for input and output images.
- [ ] Display expected input image dimensions and format for each model.
- [ ] Embed the input image within the window instead of opening it in a new dialog.
- [ ] Implement frontend validation to check if the uploaded image has correct dimensions before sending it to the server.
- [ ] Change the default behavior to not run the model automatically; allow the user to click "Run" when ready.
- [ ] Implement a pop-up error message when the uploaded image dimensions do not match the expected ones.
- [ ] Include an animation during model testing to provide visual feedback and avoid a static appearance.

**Comment by oeway** [comment]
@Nanguage The CI is failing right now because format issue, you can run `npm run format` to fix this before your commits.

**Comment by Nanguage** [comment]
## Updates 2023.09.25

- [x] Display expected input image dimensions and format for each model.
- [x] Embed the input image within the window instead of opening it in a new dialog.
- [x] Implement frontend validation to check if the uploaded image has correct dimensions before sending it to the server.
- [x] Change the default behavior to not run the model automatically; allow the user to click "Run" when ready.
- [x] Implement a pop-up error message when the uploaded image dimensions do not match the expected ones.
- [x] Include an animation during model testing to provide visual feedback and avoid a static appearance.
- [x] Add minimal_ui mode to the run_button, hide the 'show source code' and 'EditButton' in the minimal_ui mode 

@oeway @cfusterbarcelo 

https://deploy-preview-352--bioimage.netlify.app/#/

**Comment by oeway** [comment]
@Nanguage The CI is failing due to format, please update it so we can proceed with the merging.

**Comment by oeway** [comment]
@Nanguage I just update the itk-vtk-viewer so it's now support synchronized view:
```python
from imjoy_rpc import api
import numpy as np

image1 = np.random.randint(0, 255, (30, 30, 20))
image2 = np.random.randint(0, 255, (30, 30, 20))

async def setup():
    viewer1 = await api.createWindow(src="https://oeway.github.io/itk-vtk-viewer")
    await viewer1.setImage(image1)
    viewer2 = await api.createWindow(src="https://oeway.github.io/itk-vtk-viewer")
    await viewer2.setImage(image2)

    await viewer1.sync(viewer2)
    await viewer2.sync(viewer1)
api.export({"setup": setup})
```

**Comment by Nanguage** [comment]
> @Nanguage I just update the itk-vtk-viewer so it's now support synchronized view:
> 
> ```python
> from imjoy_rpc import api
> import numpy as np
> 
> image1 = np.random.randint(0, 255, (30, 30, 20))
> image2 = np.random.randint(0, 255, (30, 30, 20))
> 
> async def setup():
>     viewer1 = await api.createWindow(src="https://oeway.github.io/itk-vtk-viewer")
>     await viewer1.setImage(image1)
>     viewer2 = await api.createWindow(src="https://oeway.github.io/itk-vtk-viewer")
>     await viewer2.setImage(image2)
> 
>     await viewer1.sync(viewer2)
>     await viewer2.sync(viewer1)
> api.export({"setup": setup})
> ```

Perhaps we can provide a checkbox for users to choose whether to synchronize the input and output image viewers.

**Pull request merged**
