### PR TITLE
Change models to bioimage-models

### PR DESCRIPTION
**Pull request by oeway**
I changed the `models` repo name to `bioimage-models` such that when one clone it or fork it, it will be clear that this is models for bioimage.io.

### CODE REVIEW

**Review by MartinHjelmare — APPROVED** [review]

**Comment by MartinHjelmare** [comment]
Should it be `bioimage-io-models`? The application specific repos all contain `bioimage-io`.

**Comment by oeway** [comment]
> Should it be `bioimage-io-models`? The application specific repos all contain `bioimage-io`.

Thought about that, but `bioimage-io-models` does not read well as `bioimage-models` to me. Yes, all the application repos has `bioimage-io`, and considering this repo is a bit more unique (the "root" directory of the model repository), to make it different from application repos, perhaps it's better to make it an exception?

**Comment by MartinHjelmare** [comment]
I'm mostly thinking about keeping the brand name intact and being consistent about that.

`bioimage` is not our "brand" name.

We already distinguish this repo name by inverting the order where `bioimage` is placed compared to the application repos.

**Comment by oeway** [comment]
> I'm mostly thinking about keeping the brand name intact and being consistent about that.
> 
> We already distinguish this repo name by inverting the order where `bioimage` is placed compared to the application repos.

OK, let's do `bioimage-io-models`.

**Pull request merged**
