### PR TITLE
Add source field

### PR DESCRIPTION
**Pull request by oeway**
For datasets, we expose the source field in the upload form. For simplicity, we show this field for disregard the types.

cc @esgomezm

### CODE REVIEW

**Comment by esgomezm** [comment]
Thank you Wei! 

So now, what I see is that even for datasets, the upload functionality, first of all, asks to upload something. In the case of datasets, is it really necessary to manually create a yaml file instead of using only the fields from the upload functionality? If so, I would create a template for sure at least for datasets. 

If I provide the zenodo URL in `Option 3: Load from DOI or URL`, it outputs an error message because it's looking for an RDF file. Could we change the message to something like `Option 3: Load the RDF file from DOI or URL`?

**Comment by oeway** [comment]
Hey @esgomezm Thanks for looking into it. Can you try option2 to fill it manually?

**Comment by esgomezm** [comment]
When I try it, I get the following message: 

Screenshot 2022-02-17 at 15 52 30

**Comment by oeway** [comment]
I guess I missed to actually integrate the source field information, now it should been fixed. Merging now since it should be safe, please open an issue if this doesn't work.

**Pull request merged**
